// 软件数据。新增软件直接在这里追加对象即可。
// os: 'windows' | 'macos' | 'cross'
// category: 'system' | 'disk' | 'productivity' | 'dev' | 'media' | 'network' | 'security' | 'files' | 'browser'
// price: 'free' | 'freemium' | 'paid' | 'oss' (开源)

const SOFTWARE = [
  // ========== 系统工具 / System ==========
  { name: 'Revo Uninstaller', desc: '彻底卸载程序，扫描并清理注册表残留和遗留文件，比 Windows 自带的卸载强很多。', url: 'https://www.revouninstaller.com/', os: 'windows', category: 'system', price: 'freemium' },
  { name: 'AppCleaner', desc: '在 Mac 上彻底卸载应用，找出所有相关文件一并删除。', url: 'https://freemacsoft.net/appcleaner/', os: 'macos', category: 'system', price: 'free' },
  { name: 'PowerToys', desc: '微软官方出品的实用工具集：FancyZones 窗口分屏、PowerRename 批量改名、PowerToys Run 启动器、键盘重映射等。', url: 'https://learn.microsoft.com/windows/powertoys/', os: 'windows', category: 'system', price: 'oss' },
  { name: 'Process Explorer', desc: 'Sysinternals 出品的"超级任务管理器"，看进程详细信息、句柄、DLL，定位资源占用。', url: 'https://learn.microsoft.com/sysinternals/downloads/process-explorer', os: 'windows', category: 'system', price: 'free' },
  { name: 'Autoruns', desc: 'Sysinternals 出品，列出所有开机自启项（包括隐藏的服务、计划任务、驱动），关闭流氓自启。', url: 'https://learn.microsoft.com/sysinternals/downloads/autoruns', os: 'windows', category: 'system', price: 'free' },
  { name: 'AutoHotkey', desc: '强大的键盘/鼠标/窗口自动化脚本工具，自定义热键、文本扩展、宏。', url: 'https://www.autohotkey.com/', os: 'windows', category: 'system', price: 'oss' },
  { name: 'Karabiner-Elements', desc: 'Mac 上最强的键盘重映射工具，CapsLock 改 Esc、组合键、复杂修饰。', url: 'https://karabiner-elements.pqrs.org/', os: 'macos', category: 'system', price: 'oss' },
  { name: 'Hammerspoon', desc: 'Mac 上用 Lua 脚本控制系统的自动化框架，窗口管理、热键、自动化无所不能。', url: 'https://www.hammerspoon.org/', os: 'macos', category: 'system', price: 'oss' },
  { name: 'BetterTouchTool', desc: 'Mac 上自定义触控板手势、键盘快捷键、Touch Bar，可玩性极高。', url: 'https://folivora.ai/', os: 'macos', category: 'system', price: 'paid' },
  { name: 'iStat Menus', desc: 'Mac 菜单栏系统监控：CPU、内存、网络、温度、电池、风扇全都一目了然。', url: 'https://bjango.com/mac/istatmenus/', os: 'macos', category: 'system', price: 'paid' },
  { name: 'Stats', desc: 'iStat Menus 的免费开源替代，菜单栏显示系统状态。', url: 'https://github.com/exelban/stats', os: 'macos', category: 'system', price: 'oss' },
  { name: 'Rectangle', desc: 'Mac 窗口分屏工具（替代已停更的 Spectacle），快捷键拖动窗口到屏幕一半/四分之一。', url: 'https://rectangleapp.com/', os: 'macos', category: 'system', price: 'oss' },
  { name: 'AltTab', desc: '把 Windows 风格的 Alt+Tab 切换器带到 Mac，按窗口而非应用切换。', url: 'https://alt-tab-macos.netlify.app/', os: 'macos', category: 'system', price: 'oss' },
  { name: 'Bartender', desc: 'Mac 菜单栏图标整理工具，把不常用的图标隐藏起来。', url: 'https://www.macbartender.com/', os: 'macos', category: 'system', price: 'paid' },
  { name: 'CrystalDiskInfo', desc: '查看硬盘 SMART 健康状态、温度、通电时长，预警老化磁盘。', url: 'https://crystalmark.info/en/software/crystaldiskinfo/', os: 'windows', category: 'system', price: 'oss' },
  { name: 'HWiNFO', desc: '极其详细的硬件信息和实时监控，CPU/GPU/主板/电源全覆盖。', url: 'https://www.hwinfo.com/', os: 'windows', category: 'system', price: 'free' },
  { name: 'coconutBattery', desc: '查看 Mac 电池健康度、循环次数、原厂容量。', url: 'https://www.coconut-flavour.com/coconutbattery/', os: 'macos', category: 'system', price: 'freemium' },

  // ========== 磁盘与文件 / Disk & Files ==========
  { name: 'TreeSize Free', desc: '可视化扫描磁盘占用，按文件夹大小排序，找出谁吃掉了你的磁盘空间。', url: 'https://www.jam-software.com/treesize_free', os: 'windows', category: 'disk', price: 'freemium' },
  { name: 'WizTree', desc: '比 TreeSize 快得多的磁盘分析器，直接读 NTFS 文件表，几秒钟扫完整盘。', url: 'https://diskanalyzer.com/', os: 'windows', category: 'disk', price: 'freemium' },
  { name: 'WinDirStat', desc: '经典磁盘可视化工具，方块图直观展示每个文件占用比例。', url: 'https://windirstat.net/', os: 'windows', category: 'disk', price: 'oss' },
  { name: 'DaisyDisk', desc: 'Mac 上颜值最高的磁盘可视化工具，环形图清晰展示空间分布。', url: 'https://daisydiskapp.com/', os: 'macos', category: 'disk', price: 'paid' },
  { name: 'OmniDiskSweeper', desc: 'Mac 上免费的磁盘分析工具，列表式展示文件夹大小。', url: 'https://www.omnigroup.com/more', os: 'macos', category: 'disk', price: 'free' },
  { name: 'Everything', desc: 'Windows 上最快的文件搜索工具，毫秒级即时搜索，按名称、扩展名、大小过滤。', url: 'https://www.voidtools.com/', os: 'windows', category: 'files', price: 'free' },
  { name: 'TeraCopy', desc: '替代 Windows 默认的文件复制，速度更快、可暂停、错误重试、校验完整性。', url: 'https://www.codesector.com/teracopy', os: 'windows', category: 'files', price: 'freemium' },
  { name: 'FreeFileSync', desc: '强大的文件夹同步和备份工具，支持双向同步、镜像、版本控制。', url: 'https://freefilesync.org/', os: 'cross', category: 'files', price: 'oss' },
  { name: '7-Zip', desc: '压缩率最高的免费开源压缩工具，支持几乎所有格式。', url: 'https://www.7-zip.org/', os: 'windows', category: 'files', price: 'oss' },
  { name: 'Bandizip', desc: '颜值在线的压缩工具，速度快、广告少、支持密码恢复。', url: 'https://www.bandisoft.com/bandizip/', os: 'cross', category: 'files', price: 'freemium' },
  { name: 'Keka', desc: 'Mac 上的优秀压缩工具，支持 7z、Zip、Tar、RAR 等格式。', url: 'https://www.keka.io/', os: 'macos', category: 'files', price: 'freemium' },
  { name: 'The Unarchiver', desc: 'Mac 上最受欢迎的免费解压工具，支持 RAR、7z 等多种格式。', url: 'https://theunarchiver.com/', os: 'macos', category: 'files', price: 'free' },
  { name: 'Files', desc: '现代化的 Windows 文件管理器替代，支持多标签、暗色模式、Git 集成。', url: 'https://files.community/', os: 'windows', category: 'files', price: 'oss' },
  { name: 'Listary', desc: 'Windows 文件管理器加速器，文件搜索 + 启动器二合一。', url: 'https://www.listary.com/', os: 'windows', category: 'files', price: 'freemium' },
  { name: 'Snipaste', desc: '截图 + 贴图工具，可以把截图钉在屏幕上当参考。', url: 'https://www.snipaste.com/', os: 'cross', category: 'files', price: 'freemium' },
  { name: 'ShareX', desc: '功能极其全面的截图、录屏、上传工具，全部免费开源。', url: 'https://getsharex.com/', os: 'windows', category: 'files', price: 'oss' },
  { name: 'CleanShot X', desc: 'Mac 上颜值和功能都顶级的截图录屏工具。', url: 'https://cleanshot.com/', os: 'macos', category: 'files', price: 'paid' },

  // ========== 效率 / Productivity ==========
  { name: 'Ditto', desc: '剪贴板历史管理器，记录每次复制的内容，按需粘贴。', url: 'https://ditto-cp.sourceforge.io/', os: 'windows', category: 'productivity', price: 'oss' },
  { name: 'Maccy', desc: 'Mac 上的剪贴板历史工具，简洁开源。', url: 'https://maccy.app/', os: 'macos', category: 'productivity', price: 'oss' },
  { name: 'Raycast', desc: 'Mac 上最强的启动器，可装大量插件做计算/翻译/管窗口/操作 GitHub 等。Windows 版已发布。', url: 'https://www.raycast.com/', os: 'cross', category: 'productivity', price: 'freemium' },
  { name: 'Alfred', desc: 'Mac 老牌启动器，工作流系统极其强大。', url: 'https://www.alfredapp.com/', os: 'macos', category: 'productivity', price: 'freemium' },
  { name: 'Flow Launcher', desc: 'Windows 上的开源启动器，类似 Alfred/Raycast，支持插件扩展。', url: 'https://www.flowlauncher.com/', os: 'windows', category: 'productivity', price: 'oss' },
  { name: 'Wox', desc: 'Windows 经典开源启动器，Flow Launcher 的前身。', url: 'http://www.wox.one/', os: 'windows', category: 'productivity', price: 'oss' },
  { name: 'Obsidian', desc: '基于 Markdown 的笔记工具，支持双向链接、知识图谱、强大插件生态。', url: 'https://obsidian.md/', os: 'cross', category: 'productivity', price: 'freemium' },
  { name: 'Logseq', desc: '开源大纲笔记，类似 Roam Research，本地文件、隐私优先。', url: 'https://logseq.com/', os: 'cross', category: 'productivity', price: 'oss' },
  { name: 'Notion', desc: '集笔记、看板、数据库于一体的全能工作空间。', url: 'https://www.notion.so/', os: 'cross', category: 'productivity', price: 'freemium' },
  { name: 'Joplin', desc: '开源的笔记工具，支持端到端加密、多端同步、Markdown 编辑。', url: 'https://joplinapp.org/', os: 'cross', category: 'productivity', price: 'oss' },
  { name: 'Anki', desc: '基于间隔重复算法的记忆卡片应用，背单词/学习的神器。', url: 'https://apps.ankiweb.net/', os: 'cross', category: 'productivity', price: 'oss' },
  { name: 'Zotero', desc: '免费的文献管理工具，自动抓取元数据、生成引用、协作。', url: 'https://www.zotero.org/', os: 'cross', category: 'productivity', price: 'oss' },

  // ========== 开发 / Dev ==========
  { name: 'Visual Studio Code', desc: '现代代码编辑器之王，插件生态丰富，免费跨平台。', url: 'https://code.visualstudio.com/', os: 'cross', category: 'dev', price: 'oss' },
  { name: 'Cursor', desc: '基于 VS Code 的 AI 编辑器，深度集成 LLM 写代码。', url: 'https://cursor.com/', os: 'cross', category: 'dev', price: 'freemium' },
  { name: 'Windows Terminal', desc: '微软官方现代化终端，支持多标签、GPU 加速、PowerShell/WSL/Cmd 都能装。', url: 'https://github.com/microsoft/terminal', os: 'windows', category: 'dev', price: 'oss' },
  { name: 'iTerm2', desc: 'Mac 上替代默认 Terminal 的事实标准，分屏、热键、丰富配置。', url: 'https://iterm2.com/', os: 'macos', category: 'dev', price: 'oss' },
  { name: 'Warp', desc: '现代化的 AI 终端，自带 AI 助手、命令补全、协作。', url: 'https://www.warp.dev/', os: 'cross', category: 'dev', price: 'freemium' },
  { name: 'Git', desc: '版本控制系统标配，必装。', url: 'https://git-scm.com/', os: 'cross', category: 'dev', price: 'oss' },
  { name: 'GitHub Desktop', desc: 'GitHub 官方 Git GUI 客户端，新手友好。', url: 'https://desktop.github.com/', os: 'cross', category: 'dev', price: 'oss' },
  { name: 'Sourcetree', desc: 'Atlassian 出品的免费 Git GUI 客户端，可视化分支、提交、合并。', url: 'https://www.sourcetreeapp.com/', os: 'cross', category: 'dev', price: 'free' },
  { name: 'Docker Desktop', desc: '本地跑容器、做开发环境隔离的标配。', url: 'https://www.docker.com/products/docker-desktop/', os: 'cross', category: 'dev', price: 'freemium' },
  { name: 'Postman', desc: 'API 调试和测试工具，请求集合、环境变量、自动化测试。', url: 'https://www.postman.com/', os: 'cross', category: 'dev', price: 'freemium' },
  { name: 'Insomnia', desc: 'Postman 的开源替代，更轻、UI 更现代。', url: 'https://insomnia.rest/', os: 'cross', category: 'dev', price: 'oss' },
  { name: 'Hoppscotch', desc: '轻量级 Web API 客户端，浏览器里就能用，开源免费。', url: 'https://hoppscotch.io/', os: 'cross', category: 'dev', price: 'oss' },
  { name: 'DBeaver', desc: '通用数据库 GUI 客户端，支持几乎所有主流数据库。', url: 'https://dbeaver.io/', os: 'cross', category: 'dev', price: 'oss' },
  { name: 'TablePlus', desc: '颜值高、性能好的多数据库 GUI，付费但好用。', url: 'https://tableplus.com/', os: 'cross', category: 'dev', price: 'freemium' },
  { name: 'Sublime Merge', desc: '极快的 Git 客户端，搜索、diff、log 都顺滑。', url: 'https://www.sublimemerge.com/', os: 'cross', category: 'dev', price: 'paid' },
  { name: 'WinSCP', desc: 'Windows 经典 SFTP/FTP 客户端，可视化上传下载。', url: 'https://winscp.net/', os: 'windows', category: 'dev', price: 'oss' },
  { name: 'Cyberduck', desc: '跨平台的 FTP/SFTP/S3/云存储客户端。', url: 'https://cyberduck.io/', os: 'cross', category: 'dev', price: 'oss' },
  { name: 'Transmit', desc: 'Mac 上颜值最高的 FTP/SFTP/云存储客户端。', url: 'https://panic.com/transmit/', os: 'macos', category: 'dev', price: 'paid' },
  { name: 'Mockoon', desc: '本地 API mock 工具，几秒搭起一个假的接口服务。', url: 'https://mockoon.com/', os: 'cross', category: 'dev', price: 'oss' },
  { name: 'Homebrew', desc: 'Mac/Linux 上的事实标准包管理器，brew install 一句搞定。', url: 'https://brew.sh/', os: 'cross', category: 'dev', price: 'oss' },
  { name: 'Scoop', desc: 'Windows 上的命令行包管理器，绿色安装到用户目录。', url: 'https://scoop.sh/', os: 'windows', category: 'dev', price: 'oss' },
  { name: 'Chocolatey', desc: 'Windows 老牌包管理器，软件库丰富。', url: 'https://chocolatey.org/', os: 'windows', category: 'dev', price: 'freemium' },
  { name: 'winget', desc: '微软官方包管理器（Windows 11 自带），命令行装软件。', url: 'https://learn.microsoft.com/windows/package-manager/', os: 'windows', category: 'dev', price: 'oss' },

  // ========== 多媒体 / Media ==========
  { name: 'VLC', desc: '万能播放器，几乎支持所有视频/音频格式。', url: 'https://www.videolan.org/vlc/', os: 'cross', category: 'media', price: 'oss' },
  { name: 'mpv', desc: '极简但功能强大的命令行风格播放器，性能极佳。', url: 'https://mpv.io/', os: 'cross', category: 'media', price: 'oss' },
  { name: 'PotPlayer', desc: 'Windows 上功能最丰富的视频播放器，硬解、多音轨、字幕完美。', url: 'https://potplayer.daum.net/', os: 'windows', category: 'media', price: 'free' },
  { name: 'IINA', desc: 'Mac 原生现代视频播放器，基于 mpv，颜值在线。', url: 'https://iina.io/', os: 'macos', category: 'media', price: 'oss' },
  { name: 'foobar2000', desc: '轻量、高度可定制的音频播放器，烧友最爱。', url: 'https://www.foobar2000.org/', os: 'cross', category: 'media', price: 'free' },
  { name: 'HandBrake', desc: '免费开源的视频转码工具，压片必备。', url: 'https://handbrake.fr/', os: 'cross', category: 'media', price: 'oss' },
  { name: 'OBS Studio', desc: '专业级直播和录屏软件，免费开源。', url: 'https://obsproject.com/', os: 'cross', category: 'media', price: 'oss' },
  { name: 'Audacity', desc: '免费开源的多轨音频编辑器。', url: 'https://www.audacityteam.org/', os: 'cross', category: 'media', price: 'oss' },
  { name: 'DaVinci Resolve', desc: '好莱坞级别的视频剪辑/调色软件，免费版功能也极其强大。', url: 'https://www.blackmagicdesign.com/products/davinciresolve', os: 'cross', category: 'media', price: 'freemium' },
  { name: 'GIMP', desc: 'Photoshop 的免费开源替代，功能全面。', url: 'https://www.gimp.org/', os: 'cross', category: 'media', price: 'oss' },
  { name: 'Krita', desc: '免费开源的数字绘画软件，画师友好。', url: 'https://krita.org/', os: 'cross', category: 'media', price: 'oss' },
  { name: 'Inkscape', desc: 'Illustrator 的开源替代，做矢量图。', url: 'https://inkscape.org/', os: 'cross', category: 'media', price: 'oss' },
  { name: 'Paint.NET', desc: '比 Windows 画图强大、比 Photoshop 简单的图像编辑器。', url: 'https://www.getpaint.net/', os: 'windows', category: 'media', price: 'free' },
  { name: 'IrfanView', desc: 'Windows 上极快的图片查看器和批量处理工具。', url: 'https://www.irfanview.com/', os: 'windows', category: 'media', price: 'free' },
  { name: 'Sumatra PDF', desc: '极简轻量的 PDF/电子书阅读器，秒开。', url: 'https://www.sumatrapdfreader.org/', os: 'windows', category: 'media', price: 'oss' },

  // ========== 网络 / Network ==========
  { name: 'qBittorrent', desc: '免费开源无广告的 BT 下载工具，uTorrent 的最佳替代。', url: 'https://www.qbittorrent.org/', os: 'cross', category: 'network', price: 'oss' },
  { name: 'aria2', desc: '命令行下载利器，支持多线程、HTTP/FTP/BT/磁力。', url: 'https://aria2.github.io/', os: 'cross', category: 'network', price: 'oss' },
  { name: 'Wireshark', desc: '专业网络协议分析器，抓包必备。', url: 'https://www.wireshark.org/', os: 'cross', category: 'network', price: 'oss' },
  { name: 'Fiddler', desc: 'HTTP/HTTPS 抓包调试，前后端联调神器。', url: 'https://www.telerik.com/fiddler', os: 'windows', category: 'network', price: 'freemium' },
  { name: 'Charles', desc: 'Mac 上的 HTTP 抓包工具，移动端调试也好用。', url: 'https://www.charlesproxy.com/', os: 'cross', category: 'network', price: 'paid' },
  { name: 'Proxyman', desc: 'Mac 原生的现代化 HTTP 抓包工具，颜值高于 Charles。', url: 'https://proxyman.io/', os: 'macos', category: 'network', price: 'freemium' },
  { name: 'Rufus', desc: 'Windows 上做启动 U 盘的最快工具，比官方工具好用。', url: 'https://rufus.ie/', os: 'windows', category: 'network', price: 'oss' },
  { name: 'balenaEtcher', desc: '跨平台的 USB/SD 卡镜像烧录工具，UI 友好。', url: 'https://etcher.balena.io/', os: 'cross', category: 'network', price: 'oss' },

  // ========== 安全 / Security ==========
  { name: 'KeePassXC', desc: '开源本地密码管理器，安全可控，社区活跃。', url: 'https://keepassxc.org/', os: 'cross', category: 'security', price: 'oss' },
  { name: 'Bitwarden', desc: '云端密码管理器，免费版基本够用，支持自托管。', url: 'https://bitwarden.com/', os: 'cross', category: 'security', price: 'freemium' },
  { name: '1Password', desc: '颜值最高、体验最好的付费密码管理器。', url: 'https://1password.com/', os: 'cross', category: 'security', price: 'paid' },
  { name: 'VeraCrypt', desc: '免费开源的磁盘加密工具，TrueCrypt 的继承者。', url: 'https://www.veracrypt.fr/', os: 'cross', category: 'security', price: 'oss' },
  { name: 'Cryptomator', desc: '为云存储设计的加密工具，端到端加密同步盘里的文件。', url: 'https://cryptomator.org/', os: 'cross', category: 'security', price: 'oss' },
  { name: 'Malwarebytes', desc: '专业反恶意软件，作为 Windows Defender 的二次确认。', url: 'https://www.malwarebytes.com/', os: 'cross', category: 'security', price: 'freemium' },

  // ========== 浏览器 / Browser ==========
  { name: 'Brave', desc: '默认拦截广告和追踪的浏览器，基于 Chromium。', url: 'https://brave.com/', os: 'cross', category: 'browser', price: 'oss' },
  { name: 'Arc', desc: '颠覆传统浏览器交互的新派浏览器，标签页、空间组织极有创意。', url: 'https://arc.net/', os: 'cross', category: 'browser', price: 'free' },
  { name: 'Firefox', desc: '坚持隐私优先的非 Chromium 浏览器。', url: 'https://www.mozilla.org/firefox/', os: 'cross', category: 'browser', price: 'oss' },
  { name: 'Vivaldi', desc: '高度可定制的浏览器，老 Opera 团队出品。', url: 'https://vivaldi.com/', os: 'cross', category: 'browser', price: 'free' }
];
